version: '3.7'

services:
  db:
    image: docker.io/postgres:15-alpine
    volumes:
      - db-vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=academia
      - POSTGRES_PASSWORD=root
volumes:
  db-vol: